### PR TITLE
Different regex for windows

### PR DESCRIPTION
**Pull request by eisisig**
Added a windows check and then added different regex for windows checks

### CODE REVIEW

**Comment by seantimm** [comment]
I didn't notice your pull request until I submitted mine (https://github.com/toptal/component-resolver-webpack/pull/2), but I used path.sep instead of evaluating the platform which feels a bit cleaner (although probably doesn't matter much in the end).

**Comment by eisisig** [comment]
No prop... It sounds more like the right thing ;)

**Comment by kossnocorp** [comment]
@eisisig @seantimm thanks, guys! Please sorry for delay, I fucked up with GitHub notifications.

Here is new pull-request with AppVeyor integration: https://github.com/toptal/component-resolver-webpack/pull/6

**Comment by kossnocorp** [comment]
@eisisig @seantimm thank you, guys! New [npm package version was released](https://github.com/toptal/component-resolver-webpack/blob/master/docs/CHANGELOG.md#v040-oct-7-2015) as `v0.4.0`.

**Pull request closed without merging**
